# This is a basic workflow to help you get started with Actions

name: osMatrix

on: 
  workflow_dispatch

jobs: 
  message:
    strategy:
      matrix:
        os: 
         - ubuntu-latest
         - windows-latest
         - macos-latest
    runs-on: ${{ matrix.os }}     
    steps:
      - name: say hello to the os
        run: echo "Hello from ${{ matrix.os }}"     
